"""Bake the saved artwork into QVGA PNG + VXA8 + embedded RGB565/A8.

No online generation is needed to rebuild. Source cuts reflect the saved
artwork's actual panel seams, rather than assuming the requested dimensions.
"""
from pathlib import Path
import json
import struct
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets"


def encode(image):
    image = image.convert("RGBA")
    pixels = list(image.get_flattened_data() if hasattr(image, 'get_flattened_data') else image.getdata())
    rgb = [((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3) for r,g,b,a in pixels]
    alpha = bytes(a for r,g,b,a in pixels)
    opaque = min(alpha) == 255
    data = struct.pack('<4sHHBBH', b'VXA8', image.width, image.height, int(opaque), 1, 12)
    data += struct.pack('<' + 'H' * len(rgb), *rgb)
    if not opaque:
        data += alpha
    return data


def main():
    (ASSETS / 'backgrounds').mkdir(exist_ok=True)
    (ASSETS / 'sprites').mkdir(exist_ok=True)
    (ASSETS / 'runtime').mkdir(exist_ok=True)
    env = Image.open(ASSETS / 'source/environments.png')
    sprites = Image.open(ASSETS / 'source/characters.png').convert('RGBA')
    outputs = []
    for name, y0, y1 in [('library',0,472), ('terrace',472,968), ('village',968,1536)]:
        crop = env.crop((0,y0,env.width,y1))
        # Center crop to portrait 3:4; sample without interpolating pixel art.
        width = crop.height * 3 // 4
        x = (crop.width - width) // 2
        crop = crop.crop((x,0,x+width,crop.height)).resize((240,320),Image.Resampling.NEAREST)
        crop.save(ASSETS / f'backgrounds/{name}.png')
        outputs.append((name,crop))

    atlas = Image.new('RGBA',(320,384))
    frames = []
    names = ['hero','sage','witch','companion']
    for row in range(4):
        for col in range(4):
            cut = sprites.crop((col*sprites.width//4,row*sprites.height//4,
                (col+1)*sprites.width//4,(row+1)*sprites.height//4))
            bounds = cut.getchannel('A').point(lambda a:255 if a>64 else 0).getbbox()
            if not bounds:
                raise ValueError(f'Empty source sprite {row},{col}')
            cut = cut.crop(bounds)
            # Companion silhouettes intentionally smaller; knight remains tall.
            maxw,maxh = (70,88) if row<3 else [(34,44),(34,32),(25,23),(55,84)][col]
            scale = min(maxw/cut.width,maxh/cut.height)
            cut = cut.resize((max(1,round(cut.width*scale)),max(1,round(cut.height*scale))),Image.Resampling.NEAREST)
            atlas.alpha_composite(cut,(col*80+(80-cut.width)//2,row*96+92-cut.height))
            frames.append({'index':row*4+col,'name':f'{names[row]}_{col}',
                'rect':[col*80,row*96,80,96],'anchor':[40,92]})
    atlas.save(ASSETS / 'sprites/characters_atlas.png')
    for name,index in [('hero_idle',0),('sage_idle',4),('witch_idle',8),
                       ('fairy',12),('duck',13),('frog',14),('knight',15)]:
        col,row=index%4,index//4
        atlas.crop((col*80,row*96,(col+1)*80,(row+1)*96)).save(ASSETS / f'sprites/{name}.png')
    outputs.append(('characters',atlas))
    header = ['// Generated by tools/generate_assets.py. Do not hand-edit.', '#pragma once', '#include <stdint.h>']
    for name,image in outputs:
        data = encode(image)
        (ASSETS / f'runtime/{name}.vxa8').write_bytes(data)
        header.append(f'alignas(4) static const uint8_t ember_{name}[] = {{')
        for offset in range(0,len(data),24):
            header.append(','.join(f'0x{v:02x}' for v in data[offset:offset+24])+',')
        header.append('};')
    (ROOT / 'src/assets_generated.h').write_text('\n'.join(header)+'\n',encoding='utf-8')
    (ASSETS / 'sprites/frames.json').write_text(json.dumps({'frame_size':[80,96],'frames':frames},indent=2),encoding='utf-8')
    animation = {'format':'VXPEngine Animation','format_version':2,'extension':'.ani..dtfe',
        'asset':'assets/sprites/characters_atlas.png','texture':'assets/sprites/characters_atlas.png',
        'source_mode':'atlas_frames','asset_kind':'character','package':'atlas+descriptor',
        'animation':{'name':'hero_walk','fps':7,'loop':True,'frame_count':4,'source_mode':'atlas_frames',
            'asset_kind':'character','selected_indices':[0,1,2,3]},
        'frames':[{'name':f'walk_{n}','x':i*80,'y':0,'width':80,'height':96,
            'source_index':n,'duration_ms':140} for n,i in enumerate([0,1,2,1])]}
    # Use the IDE's established animation descriptor shape.
    (ASSETS / 'sprites/hero_walk.ani..dtfe').write_text(json.dumps(animation,indent=2),encoding='utf-8')
    print('Baked 3 backgrounds, 16 sprite frames, 4 VXA8 resources + embedded header')


if __name__ == '__main__':
    main()
