/*
 * Copyright (c) 2026 PixelRoot32
 * Licensed under the MIT License
 *
 * @file RoomLayout.h
 * @brief Room metadata as emitted by the Tilemap Editor, plus the builder that
 *        turns it into a runtime RoomGraph<N>.
 *
 * This header is the room-graph counterpart of `physics/TileAttributes.h`'s
 * `TileBehaviorLayer`: a plain data contract the editor's C++ export writes
 * out, and which the engine reads back with no parsing and no allocation.
 * Authoring lives in the Tilemap Editor; this file only describes the shape
 * of what it emits.
 *
 * Example (what the editor generates, and how a Scene consumes it):
 * @code
 * // dungeon_rooms.h — generated by PixelRoot32 Tilemap Editor
 * static const pixelroot32::gameplay::RoomData DUNGEON_ROOMS[] = {
 *     {  0, 0, 20, 15, { 0xFFFF, 0xFFFF, 0xFFFF,      1 } },
 *     { 20, 0, 20, 15, { 0xFFFF, 0xFFFF,      0, 0xFFFF } },
 * };
 * static const pixelroot32::gameplay::RoomLayer DUNGEON_ROOM_LAYER = {
 *     DUNGEON_ROOMS, 2, 16, 16
 * };
 *
 * // MyScene::init()
 * if (buildRoomGraph(DUNGEON_ROOM_LAYER, rooms_) > 0) {
 *     setRoomGraph(&rooms_);
 *     rooms_.enterRoom(0, &camera);
 * }
 * @endcode
 *
 * Check the return value. A rejected layer builds nothing, and `enterRoom()`
 * on an empty graph is a silent no-op — the scene would run with no camera
 * bounds and no current room rather than failing loudly.
 *
 * Feature-gated by PIXELROOT32_ENABLE_GAMEPLAY_ROOM (default 0), the same flag
 * that gates RoomGraph itself.
 */

#pragma once

#include "platforms/PlatformDefaults.h"

#if PIXELROOT32_ENABLE_GAMEPLAY_ROOM

#include "gameplay/RoomGraph.h"
#include "math/Scalar.h"
#include <cstdint>

namespace pixelroot32::gameplay {

/**
 * @brief Sentinel written by the editor into an unconnected direction slot.
 *
 * Matches `Room::INVALID_ROOM` so exported data and runtime data agree on
 * what "no room" looks like.
 */
inline constexpr uint16_t kNoRoomConnection = 0xFFFF;

/**
 * @brief Sentinel `RoomGraph<N>::addRoom()` returns when the graph is full.
 *
 * Semantically distinct from kNoRoomConnection even though both are 0xFFFF —
 * one is exported data, the other a runtime return code. Kept as its own name
 * so the capacity check in buildRoomGraph() reads as what it is.
 */
inline constexpr uint16_t kGraphFull = 0xFFFF;

// These agree with RoomGraph's own sentinel by contract, not by luck. If either
// side ever moves, this breaks the build instead of silently mis-wiring rooms.
static_assert(kNoRoomConnection == static_cast<uint16_t>(Room::INVALID_ROOM),
              "kNoRoomConnection must match RoomGraph's Room::INVALID_ROOM.");
static_assert(kGraphFull == static_cast<uint16_t>(Room::INVALID_ROOM),
              "kGraphFull must match the sentinel RoomGraph::addRoom() returns.");

/**
 * @brief Widest world coordinate a room edge may reach, in either axis.
 *
 * `Scalar` is `Fixed16` on FPU-less targets (ESP32-C3), whose integer part
 * tops out at +/-32767. A room past that would wrap instead of clamping.
 */
inline constexpr int kMaxRoomWorldCoord = 32767;

/**
 * @struct RoomData
 * @brief One exported room: its tile-space rect plus four connection slots.
 *
 * Coordinates are in TILES, not world units — that is the space the editor
 * authors in. `buildRoomGraph()` multiplies by the layer's tile size to get
 * the world-space camera rect.
 *
 * Connection slots are indexed by `RoomDir` (0 = Up, 1 = Down, 2 = Left,
 * 3 = Right) and hold the target room's index within the same layer, or
 * `kNoRoomConnection` when that direction is a wall.
 *
 * Trivially copyable by design: the editor emits these as a `static const`
 * array so the linker parks them in flash, costing zero SRAM.
 */
struct RoomData {
    uint16_t originCol;       ///< Tile column of the room's left edge.
    uint16_t originRow;       ///< Tile row of the room's top edge.
    uint16_t cols;            ///< Room width in tiles.
    uint16_t rows;            ///< Room height in tiles.
    uint16_t connections[4];  ///< Target room index by direction, or kNoRoomConnection.
};

/**
 * @struct RoomLayer
 * @brief Runtime view over an exported room array — the room-graph analogue
 *        of `physics::TileBehaviorLayer`.
 *
 * Holds no ownership: `rooms` points at the editor's flash-resident array.
 */
struct RoomLayer {
    const RoomData* rooms;  ///< Pointer to the exported room array (may be null).
    uint16_t roomCount;     ///< Number of entries in `rooms`.
    uint8_t  tileWidth;     ///< Tile width in world units. MUST be >= 1.
    uint8_t  tileHeight;    ///< Tile height in world units. MUST be >= 1.
};

/**
 * @brief Populate a RoomGraph<N> from an exported room layer.
 *
 * Runs in three passes so that layer index and graph index stay identical,
 * which is what lets connections reference rooms declared later in the array:
 *
 *  1. **Validate.** A null pointer, an empty layer, a zero tile size, or any
 *     room reaching past `kMaxRoomWorldCoord` rejects the WHOLE layer and
 *     builds nothing. Partially building an invalid layer would shift the
 *     indices its connections refer to, silently rewiring the map.
 *     Validation covers every room in the layer, including ones the graph's
 *     capacity would later truncate away: a layer carrying an out-of-range
 *     room is a broken export, and a broken export fails closed rather than
 *     yielding a map that happens to look fine because the bad room fell off
 *     the end. This is deliberate, and distinct from capacity truncation
 *     (pass 2), which is a normal, reported outcome.
 *  2. **Add rooms.** Tile rects become world rects; each room's tile window
 *     is carried over verbatim.
 *  3. **Wire connections.** Slots holding `kNoRoomConnection`, or targeting a
 *     room that truncation dropped, are skipped rather than dangling.
 *
 * @tparam N     The graph's compile-time room capacity.
 * @param  layer The exported layer.
 * @param  graph The graph to fill. Rooms are appended, so a graph that already
 *               holds rooms will run out of capacity sooner. Connections are
 *               layer-local: they are remapped into graph space and can never
 *               reach a room this layer did not declare.
 * @return Number of rooms added — `layer.roomCount` when everything fit, fewer
 *         when the graph's capacity truncated it, 0 when the layer was
 *         rejected. Truncation is documented behaviour, not an error.
 */
template <uint16_t N>
uint16_t buildRoomGraph(const RoomLayer& layer, RoomGraph<N>& graph) {
    // ---- Pass 1: validate the layer as a whole -----------------------------
    if (layer.rooms == nullptr || layer.roomCount == 0) {
        return 0;
    }
    if (layer.tileWidth == 0 || layer.tileHeight == 0) {
        return 0;
    }

    const int tileW = static_cast<int>(layer.tileWidth);
    const int tileH = static_cast<int>(layer.tileHeight);

    for (uint16_t i = 0; i < layer.roomCount; ++i) {
        const RoomData& src = layer.rooms[i];
        const int farX = (static_cast<int>(src.originCol) + static_cast<int>(src.cols)) * tileW;
        const int farY = (static_cast<int>(src.originRow) + static_cast<int>(src.rows)) * tileH;
        if (farX > kMaxRoomWorldCoord || farY > kMaxRoomWorldCoord) {
            return 0;
        }
    }

    // ---- Pass 2: tile-space rects become world-space camera rects ----------
    // `baseIdx` is where the layer's room 0 landed in the graph. It is only 0
    // when the graph started empty; appending onto a populated graph shifts
    // every layer-local index by this offset.
    uint16_t added   = 0;
    uint16_t baseIdx = 0;

    for (uint16_t i = 0; i < layer.roomCount; ++i) {
        const RoomData& src = layer.rooms[i];

        const int minX = static_cast<int>(src.originCol) * tileW;
        const int minY = static_cast<int>(src.originRow) * tileH;
        const int maxX = (static_cast<int>(src.originCol) + static_cast<int>(src.cols)) * tileW;
        const int maxY = (static_cast<int>(src.originRow) + static_cast<int>(src.rows)) * tileH;

        const uint16_t idx = graph.addRoom(math::toScalar(minX), math::toScalar(minY),
                                           math::toScalar(maxX), math::toScalar(maxY));
        if (idx == kGraphFull) {
            break;  // stop here so the remaining layer indices stay contiguous
        }
        if (added == 0) {
            baseIdx = idx;
        }

        graph.setTileWindow(idx,
                            static_cast<int16_t>(src.originCol),
                            static_cast<int16_t>(src.originRow),
                            static_cast<int16_t>(src.cols),
                            static_cast<int16_t>(src.rows));
        ++added;
    }

    // ---- Pass 3: wire connections now that every index exists --------------
    // Connection targets are layer-local, so they are bounds-checked against
    // `added` (layer space) and then shifted into graph space by `baseIdx`.
    // Using the raw layer index here would connect the wrong rooms — and could
    // write edges into rooms this layer never named.
    for (uint16_t i = 0; i < added; ++i) {
        const RoomData& src = layer.rooms[i];
        for (uint8_t dir = 0; dir < 4; ++dir) {
            const uint16_t target = src.connections[dir];
            if (target == kNoRoomConnection || target >= added) {
                continue;  // wall, corrupt target, or a room truncation dropped
            }
            graph.connect(static_cast<uint16_t>(baseIdx + i),
                          static_cast<uint16_t>(baseIdx + target),
                          static_cast<RoomDir>(dir));
        }
    }

    return added;
}

} // namespace pixelroot32::gameplay

#endif // PIXELROOT32_ENABLE_GAMEPLAY_ROOM
