"""Deterministic original pixel artwork; no frames ripped from the reference video."""
from pathlib import Path
import random
import json
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'assets'
OUT.mkdir(exist_ok=True)
rng = random.Random(481388)
images = {}
for name, base in [('brick',(66,53,47)),('wood',(66,47,40)),('stone',(49,53,52)),('floor',(43,39,37)),('gate',(61,38,29))]:
    im=Image.new('RGBA',(64,64)); d=ImageDraw.Draw(im)
    for y in range(64):
        for x in range(64):
            n=rng.randint(-11,11)
            mortar=(y%16<2 or (x+(16 if y//16%2 else 0))%32<2) if name=='brick' else False
            if name in ('wood','gate'): mortar=x%12<2 or y in (15,46)
            if name=='stone': mortar=y%24<2 or (x+(12 if y//24%2 else 0))%24<2
            c=tuple(max(0,min(255,v+n-(22 if mortar else 0))) for v in base)
            d.point((x,y),fill=c+(255,))
    if name=='gate':
        for y in (16,45):
            d.line((0,y,63,y),fill=(98,69,46),width=3)
            for x in range(4,64,12):d.point((x,y),fill=(177,143,99))
    images[name]=im
for f in range(2):
    im=Image.new('RGBA',(48,64));d=ImageDraw.Draw(im)
    # Ragged military coat, pallid face, outstretched arms and walking legs.
    shift=f*2
    d.polygon([(13,22),(32,22),(36,44),(28,48),(13,44)],fill=(57,64,61))
    d.polygon([(15,43),(23,44),(22-shift,62),(13-shift,62)],fill=(41,43,42))
    d.polygon([(25,44),(32,43),(37+shift,61),(29+shift,63)],fill=(38,40,40))
    d.polygon([(15,22),(8,23),(2,39),(6,44),(11,39),(19,26)],fill=(78,85,76))
    d.polygon([(30,22),(37,24),(46,36),(43,42),(36,36),(27,26)],fill=(67,77,68))
    d.rectangle((1,39,6,45),fill=(150,152,116));d.rectangle((42,37,46,44),fill=(150,152,116))
    d.rectangle((19,7,29,23),fill=(145,151,124))
    d.polygon([(18,9),(20,3),(29,4),(32,10),(30,14),(28,8),(19,10)],fill=(48,49,44))
    d.rectangle((18,10,21,13),fill=(207,63,36));d.rectangle((27,10,30,13),fill=(226,86,36))
    d.line((21,19,28,19),fill=(48,25,24),width=2)
    d.polygon([(22,25),(26,25),(28,40),(24,43)],fill=(108,39,32))
    d.line((14,28,32,29),fill=(116,119,109),width=2)
    d.line((15,36,33,37),fill=(25,31,29),width=2)
    d.rectangle((20,36,25,39),fill=(112,108,89))
    d.line((22,7,27,7),fill=(181,184,149),width=2)
    d.line((20,15,23,16),fill=(183,178,140),width=2)
    for _ in range(160):
        x,y=rng.randrange(48),rng.randrange(64)
        if im.getpixel((x,y))[3]:
            c=im.getpixel((x,y));n=rng.randint(-20,18)
            d.point((x,y),fill=tuple(max(0,min(255,v+n)) for v in c[:3])+(255,))
    images['zombie'+str(f)]=im
im=Image.new('RGBA',(112,104));d=ImageDraw.Draw(im)
# Blue work gloves and a steel pistol, drawn with a vanishing point above centre.
d.polygon([(11,103),(38,63),(55,56),(73,68),(86,103)],fill=(37,81,117))
d.polygon([(72,103),(63,70),(77,61),(95,72),(111,103)],fill=(30,65,94))
d.polygon([(38,63),(48,43),(61,40),(75,62),(65,77),(50,74)],fill=(50,101,135))
d.polygon([(47,62),(46,19),(53,6),(68,6),(77,17),(70,55),(63,67)],fill=(25,28,32))
d.polygon([(49,20),(55,9),(66,9),(72,18),(67,47),(52,50)],fill=(70,77,81))
d.rectangle((55,4,62,8),fill=(132,140,135));d.line((51,24,68,23),fill=(145,152,147),width=2)
d.polygon([(60,48),(70,53),(70,78),(62,86),(56,73)],fill=(34,36,37))
d.rectangle((56,11,63,16),fill=(13,15,18))
d.line((70,20,66,43),fill=(105,113,112),width=2)
d.line((50,55,61,58),fill=(80,143,174),width=2)
d.line((49,61,59,64),fill=(74,132,165),width=2)
for y in range(56,96,7):d.line((25,y+14,45,y+2),fill=(65,126,162),width=2)
images['pistol']=im
im=Image.new('RGBA',(48,64));d=ImageDraw.Draw(im)
d.rectangle((7,30,42,63),fill=(38,42,41));d.rounded_rectangle((10,7,38,52),radius=10,fill=(81,87,79))
d.rectangle((15,19,33,21),fill=(117,119,102));d.line((24,14,24,37),fill=(113,116,98),width=3)
images['grave']=im
im=Image.new('RGBA',(24,48));d=ImageDraw.Draw(im)
d.polygon([(12,0),(19,14),(15,23),(8,22),(4,16)],fill=(234,97,30))
d.polygon([(12,7),(15,16),(12,20),(9,16)],fill=(255,219,133))
d.rectangle((8,21,16,42),fill=(147,110,70));d.rectangle((2,43,22,47),fill=(45,34,27))
images['candle']=im
im=Image.new('RGBA',(64,48));d=ImageDraw.Draw(im)
d.rectangle((6,17,57,35),fill=(99,35,31));d.rectangle((2,26,61,42),fill=(78,29,28))
d.rectangle((7,27,30,34),fill=(135,51,39));d.rectangle((33,27,55,34),fill=(122,45,37))
d.rectangle((3,20,8,35),fill=(134,55,43));d.rectangle((55,20,61,35),fill=(130,53,42))
d.rectangle((6,42,10,47),fill=(40,29,24));d.rectangle((52,42,56,47),fill=(40,29,24))
images['sofa']=im
header=['// Generated by tools/make_assets.py. RGB565, 0xffff = transparent.','#pragma once','#include <stdint.h>']
for name,im in images.items():
    im.save(OUT/(name+'.png'))
    pixels=[]
    for r,g,b,a in (im.getpixel((x,y)) for y in range(im.height) for x in range(im.width)):
        value=65535 if a==0 else ((r>>3)<<11)|((g>>2)<<5)|(b>>3)
        pixels.append(value if value!=65535 or a==0 else 65534)
    header.append('static const uint16_t ART_'+name+'['+str(len(pixels))+']={'+','.join(hex(v) for v in pixels)+'};')
(ROOT/'src/art.h').write_text('\n'.join(header)+'\n',encoding='utf-8')
atlas=Image.new('RGBA',(96,64));atlas.paste(images['zombie0'],(0,0));atlas.paste(images['zombie1'],(48,0));atlas.save(OUT/'zombie_atlas.png')
scene=OUT/'scenes';scene.mkdir(exist_ok=True)
descriptor={'format':'VXPEngine Animation','format_version':2,'extension':'.ani..dtfe',
 'asset':'assets/zombie_atlas.png','texture':'assets/zombie_atlas.png','source_mode':'atlas_frames','asset_kind':'character',
 'package':'atlas+descriptor','preview_background':'checker','preview_zoom':3,
 'animation':{'name':'zombie_walk','fps':3,'loop':True,'frame_count':2,'source_mode':'atlas_frames','asset_kind':'character','selected_indices':[0,1]},
 'frames':[{'name':'walk_'+str(i),'x':i*48,'y':0,'width':48,'height':64,'duration_ms':400,'source_index':i} for i in range(2)]}
(scene/'zombie_walk.ani..dtfe').write_text(json.dumps(descriptor,indent=2),encoding='utf-8')
metadata={'format':'VXPEngine Asset','format_version':2,'asset':'assets/zombie_atlas.png','asset_type':'Sprite / Character',
 'size':{'width':96,'height':64},'texture':{'pixels_per_unit':1,'render_mode':'nearest','transparent':True,'pixel_mode_bits':32},
 'grid':{'width':48,'height':64,'margin':0,'spacing':0},'frames':descriptor['frames'],
 'animation':{**descriptor['animation'],'descriptor':'assets/scenes/zombie_walk.ani..dtfe'}}
(OUT/'zombie_atlas.asset.dtfe').write_text(json.dumps(metadata,indent=2),encoding='utf-8')
print('Generated',len(images),'original PNG assets and embedded RGB565 artwork')
