
/* Generated by VXPEngine - do not edit manually.
 * Identifiers for screens and components designed in the 2D workspace.
 * Regenerated whenever a scene is saved.
 */
#ifndef VXP_SCENE_BINDINGS_H
#define VXP_SCENE_BINDINGS_H

/* VXPE_GENERATED_SCENE_BINDINGS_V1 */

/* Bảng component của màn thiết kế Camera 2D — build đọc bảng này để
 * vẽ đúng vị trí/kích thước đã thiết kế. */
typedef struct VxpDesignComponent {
    const char* id;
    const char* type;
    const char* asset;
    const char* res;   /* sprite .raw đóng gói sẵn ("" nếu không có ảnh) */
    float x;
    float y;
    float rotation;
    float scale_x;
    float scale_y;
    float width;
    float height;
    int z_index;
    int visible;
} VxpDesignComponent;

/* Screens */
#define SCREEN_MAIN "scenes/main.dtfe"

/* Transitions */

/* Screen: Main */
#define MAIN_ID "main"
#define MAIN_FILE "scenes/main.dtfe"
#define MAIN_FRAME_PERSPECTIVE "none"
#define MAIN_FRAME_PROJECTION "orthographic"
#define MAIN_MOVEMENT_AXES "none"
#define MAIN_CAMERA_ANGLE 0
#define MAIN_COMPONENT_COUNT 0
#define MAIN_HAS_DESIGN 0

#define MAIN_DESIGN_COMPONENTS ((const VxpDesignComponent*)0)

/* Màn đang mở trong Camera 2D (active screen) */
#define VXP_DESIGN_ACTIVE_COMPONENTS MAIN_DESIGN_COMPONENTS
#define VXP_DESIGN_ACTIVE_COUNT MAIN_COMPONENT_COUNT
#define VXP_DESIGN_ACTIVE_HAS_DESIGN MAIN_HAS_DESIGN

#endif /* VXP_SCENE_BINDINGS_H */
