
/* Generated by VXPEngine - do not edit manually.
 * Identifiers for screens and components designed in the 2D workspace.
 * Regenerated whenever a scene is saved.
 */
#ifndef VXP_SCENE_BINDINGS_H
#define VXP_SCENE_BINDINGS_H

/* VXPE_GENERATED_SCENE_BINDINGS_V1 */

/* Bảng component của màn thiết kế Camera 2D — build đọc bảng này để
 * vẽ đúng vị trí/kích thước đã thiết kế. */
typedef struct VxpDesignComponent {
    const char* id;
    const char* type;
    const char* asset;
    const char* res;   /* sprite .raw đóng gói sẵn ("" nếu không có ảnh) */
    float x;
    float y;
    float rotation;
    float scale_x;
    float scale_y;
    float width;
    float height;
    int z_index;
    int visible;
} VxpDesignComponent;

/* Screens */
#define SCREEN_MAIN "scenes/main.dtfe"

/* Transitions */

/* Screen: Main */
#define MAIN_ID "main"
#define MAIN_FILE "scenes/main.dtfe"
#define MAIN_COMPONENT_COUNT 1
#define MAIN_HAS_DESIGN 1

#define MAIN_CAMERA2D "camera2d" /* Camera2D */
#define MAIN_CAMERA2D_X 0.0000f
#define MAIN_CAMERA2D_Y 0.0000f
#define MAIN_CAMERA2D_ROTATION 0.0000f
#define MAIN_CAMERA2D_SCALE_X 1.0000f
#define MAIN_CAMERA2D_SCALE_Y 1.0000f
#define MAIN_CAMERA2D_DISPLAY_WIDTH 0.0000f
#define MAIN_CAMERA2D_DISPLAY_HEIGHT 0.0000f
#define MAIN_CAMERA2D_RESIZABLE 1
#define MAIN_CAMERA2D_LOCK_ASPECT 0
#define MAIN_CAMERA2D_OPACITY 1.0000f
#define MAIN_CAMERA2D_Z_INDEX 0
#define MAIN_CAMERA2D_VISIBLE 1
#define MAIN_CAMERA2D_TYPE "OrthographicCamera"
#define MAIN_CAMERA2D_ASSET ""
#define MAIN_CAMERA2D_BLEND_MODE "Normal"
#define MAIN_CAMERA2D_TINT "#FFFFFFFF"
#define MAIN_CAMERA2D_MOTION_TYPE ""
#define MAIN_CAMERA2D_UI_ROLE ""
#define MAIN_CAMERA2D_INPUT_BINDING ""
#define MAIN_CAMERA2D_COMPONENT_CATEGORY "sprite"
#define MAIN_CAMERA2D_AUTOMATION_ROLE ""
#define MAIN_CAMERA2D_AUTOMATION_PHYSICS "none"
#define MAIN_CAMERA2D_COLLISION_SHAPE "bounds"
#define MAIN_CAMERA2D_EVENT_CHANNEL ""
#define MAIN_CAMERA2D_TARGET_SCREEN ""
#define MAIN_CAMERA2D_DEAD_ZONE 0.1800f
#define MAIN_CAMERA2D_SENSITIVITY 1.0000f
#define MAIN_CAMERA2D_AUTOMATION_TAGS_JSON "[]"
#define MAIN_CAMERA2D_AUTOMATION_JSON "{}"
#define MAIN_CAMERA2D_EVENT_COUNT 0
#define MAIN_CAMERA2D_EVENTS_JSON "[]"
#define MAIN_CAMERA2D_CLIPPING_MASK_JSON "{}"
#define MAIN_CAMERA2D_ANCHOR_X 0.0000f
#define MAIN_CAMERA2D_ANCHOR_Y 0.0000f
#define MAIN_CAMERA2D_KEYFRAME_COUNT 0
static const VxpDesignComponent MAIN_DESIGN_COMPONENTS[1] = {
    {"camera2d", "OrthographicCamera", "", "", 0.0000f, 0.0000f, 0.0000f, 1.0000f, 1.0000f, 0.0000f, 0.0000f, 0, 1}
};

/* Màn đang mở trong Camera 2D (active screen) */
#define VXP_DESIGN_ACTIVE_COMPONENTS MAIN_DESIGN_COMPONENTS
#define VXP_DESIGN_ACTIVE_COUNT MAIN_COMPONENT_COUNT
#define VXP_DESIGN_ACTIVE_HAS_DESIGN MAIN_HAS_DESIGN

#endif /* VXP_SCENE_BINDINGS_H */
