set(COREMRE_SOURCES
  ${_COREMRE_ROOT}/src/core/PhysicsActor.cpp
  ${_COREMRE_ROOT}/src/core/Scene.cpp
  ${_COREMRE_ROOT}/src/core/SceneManager.cpp
  ${_COREMRE_ROOT}/src/gameplay/GameplayEventBus.cpp
  ${_COREMRE_ROOT}/src/gameplay/InteractionTracker.cpp
  ${_COREMRE_ROOT}/src/gameplay/StateMachine.cpp
  ${_COREMRE_ROOT}/src/graphics/Camera2D.cpp
  ${_COREMRE_ROOT}/src/graphics/CameraEffects.cpp
  ${_COREMRE_ROOT}/src/graphics/Color.cpp
  ${_COREMRE_ROOT}/src/graphics/DirtyGrid.cpp
  ${_COREMRE_ROOT}/src/graphics/Font5x7.cpp
  ${_COREMRE_ROOT}/src/graphics/FontManager.cpp
  ${_COREMRE_ROOT}/src/graphics/StaticTilemapLayerCache.cpp
  ${_COREMRE_ROOT}/src/graphics/particles/ParticleEmitter.cpp
  ${_COREMRE_ROOT}/src/graphics/ui/UIAnchorLayout.cpp
  ${_COREMRE_ROOT}/src/graphics/ui/UIButton.cpp
  ${_COREMRE_ROOT}/src/graphics/ui/UICheckBox.cpp
  ${_COREMRE_ROOT}/src/graphics/ui/UIGridLayout.cpp
  ${_COREMRE_ROOT}/src/graphics/ui/UIHorizontalLayout.cpp
  ${_COREMRE_ROOT}/src/graphics/ui/UILabel.cpp
  ${_COREMRE_ROOT}/src/graphics/ui/UILayout.cpp
  ${_COREMRE_ROOT}/src/graphics/ui/UIManager.cpp
  ${_COREMRE_ROOT}/src/graphics/ui/UIPaddingContainer.cpp
  ${_COREMRE_ROOT}/src/graphics/ui/UIPanel.cpp
  ${_COREMRE_ROOT}/src/graphics/ui/UISprite.cpp
  ${_COREMRE_ROOT}/src/graphics/ui/UISpriteRef.cpp
  ${_COREMRE_ROOT}/src/graphics/ui/UISpriteRow.cpp
  ${_COREMRE_ROOT}/src/graphics/ui/UITouchButton.cpp
  ${_COREMRE_ROOT}/src/graphics/ui/UITouchCheckbox.cpp
  ${_COREMRE_ROOT}/src/graphics/ui/UITouchSlider.cpp
  ${_COREMRE_ROOT}/src/graphics/ui/UIVerticalLayout.cpp
  ${_COREMRE_ROOT}/src/input/ActorTouchController.cpp
  ${_COREMRE_ROOT}/src/input/TouchCalibration.cpp
  ${_COREMRE_ROOT}/src/input/TouchEventDispatcher.cpp
  ${_COREMRE_ROOT}/src/input/TouchEventQueue.cpp
  ${_COREMRE_ROOT}/src/input/TouchManager.cpp
  ${_COREMRE_ROOT}/src/input/TouchStateMachine.cpp
  ${_COREMRE_ROOT}/src/physics/CollisionPrimitives.cpp
  ${_COREMRE_ROOT}/src/physics/CollisionSystem.cpp
  ${_COREMRE_ROOT}/src/physics/KinematicActor.cpp
  ${_COREMRE_ROOT}/src/physics/RigidActor.cpp
  ${_COREMRE_ROOT}/src/physics/SensorActor.cpp
  ${_COREMRE_ROOT}/src/physics/SpatialGrid.cpp
  ${_COREMRE_ROOT}/src/physics/StaticActor.cpp
  ${_COREMRE_ROOT}/src/physics/TileCollisionBuilder.cpp
  ${_COREMRE_ROOT}/src/physics/TileConsumptionHelper.cpp
  ${_COREMRE_ROOT}/src/physics/TilePixelCollision.cpp
  ${_COREMRE_ROOT}/src/platforms/PlatformCapabilities.cpp
  ${_COREMRE_ROOT}/src/platforms/PlatformLog.cpp
)
