# Dùng core coremre đã đóng gói: include(<gói>/cmake/UseCoremre.cmake)
# sau đó target_link_libraries(<app> PRIVATE coremre) và (tùy chọn) biên dịch
# ${COREMRE_SOURCES} vào app nếu app dùng phần C++ của core.
if(NOT TARGET coremre)
  get_filename_component(_COREMRE_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
  include("${CMAKE_CURRENT_LIST_DIR}/CoremreSources.cmake")
  add_library(coremre STATIC ${COREMRE_SOURCES})
  add_library(VXPEngine::coremre ALIAS coremre)
  target_include_directories(coremre PUBLIC ${_COREMRE_ROOT}/include)
  if(MRE_SDK)
    target_include_directories(coremre PUBLIC ${MRE_SDK}/include)
  endif()
  target_compile_features(coremre PUBLIC cxx_std_17)
  target_compile_definitions(coremre PUBLIC COREMRE_PLATFORM_MRE=1 PIXELROOT32_ENABLE_PARTICLES=0 PIXELROOT32_ENABLE_DIRTY_REGIONS=1)
  set_target_properties(coremre PROPERTIES CXX_EXTENSIONS OFF POSITION_INDEPENDENT_CODE ON)
  if(CMAKE_SYSTEM_NAME STREQUAL "Generic")
    target_compile_options(coremre PRIVATE -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti)
  endif()
endif()
