
/* Generated by VXPEngine - do not edit manually.
 * Identifiers for screens and components designed in the 2D workspace.
 * Regenerated whenever a scene is saved.
 */
#ifndef VXP_SCENE_BINDINGS_H
#define VXP_SCENE_BINDINGS_H

/* VXPE_GENERATED_SCENE_BINDINGS_V1 */

/* Bảng component của màn thiết kế Camera 2D — build đọc bảng này để
 * vẽ đúng vị trí/kích thước đã thiết kế. */
typedef struct VxpDesignComponent {
    const char* id;
    const char* type;
    const char* asset;
    const char* res;   /* sprite .raw đóng gói sẵn ("" nếu không có ảnh) */
    float x;
    float y;
    float rotation;
    float scale_x;
    float scale_y;
    float width;
    float height;
    int z_index;
    int visible;
} VxpDesignComponent;

/* Screens */
#define SCREEN_MAIN "scenes/main.dtfe"

/* Transitions */

/* Screen: Main */
#define MAIN_ID "main"
#define MAIN_FILE "scenes/main.dtfe"
#define MAIN_FRAME_PERSPECTIVE "none"
#define MAIN_FRAME_PROJECTION "orthographic"
#define MAIN_MOVEMENT_AXES "none"
#define MAIN_CAMERA_ANGLE 0
#define MAIN_COMPONENT_COUNT 1
#define MAIN_HAS_DESIGN 1

#define MAIN_BACKGROUND "bg" /* Background */
#define MAIN_BACKGROUND_X 0.0000f
#define MAIN_BACKGROUND_Y 0.0000f
#define MAIN_BACKGROUND_ROTATION 0.0000f
#define MAIN_BACKGROUND_SCALE_X 1.0000f
#define MAIN_BACKGROUND_SCALE_Y 1.0000f
#define MAIN_BACKGROUND_DISPLAY_WIDTH 240.0000f
#define MAIN_BACKGROUND_DISPLAY_HEIGHT 320.0000f
#define MAIN_BACKGROUND_RESIZABLE 0
#define MAIN_BACKGROUND_LOCK_ASPECT 1
#define MAIN_BACKGROUND_OPACITY 1.0000f
#define MAIN_BACKGROUND_Z_INDEX -10
#define MAIN_BACKGROUND_VISIBLE 1
#define MAIN_BACKGROUND_TYPE "Rectangle2D"
#define MAIN_BACKGROUND_ASSET ""
#define MAIN_BACKGROUND_BACKGROUND_BITMAP ""
#define MAIN_BACKGROUND_BACKGROUND_BITMAP_MODE "Fill"
#define MAIN_BACKGROUND_BLEND_MODE "Normal"
#define MAIN_BACKGROUND_TINT "#FFFFFFFF"
#define MAIN_BACKGROUND_PADDING 0
#define MAIN_BACKGROUND_MARGIN 0
#define MAIN_BACKGROUND_CORNER_RADIUS 0.0000f
#define MAIN_BACKGROUND_TEXT ""
#define MAIN_BACKGROUND_FONT "Segoe UI"
#define MAIN_BACKGROUND_FONT_SIZE 24
#define MAIN_BACKGROUND_TEXT_COLOR "#f4f7ff"
#define MAIN_BACKGROUND_FONT_BOLD 0
#define MAIN_BACKGROUND_FONT_ITALIC 0
#define MAIN_BACKGROUND_FONT_UNDERLINE 0
#define MAIN_BACKGROUND_FONT_STRIKEOUT 0
#define MAIN_BACKGROUND_MOTION_TYPE ""
#define MAIN_BACKGROUND_UI_ROLE "Background"
#define MAIN_BACKGROUND_INPUT_BINDING ""
#define MAIN_BACKGROUND_COMPONENT_CATEGORY "background"
#define MAIN_BACKGROUND_AUTOMATION_ROLE ""
#define MAIN_BACKGROUND_AUTOMATION_PHYSICS "none"
#define MAIN_BACKGROUND_COLLISION_SHAPE "bounds"
#define MAIN_BACKGROUND_COLLISION_ENABLED 1
#define MAIN_BACKGROUND_EVENT_CHANNEL ""
#define MAIN_BACKGROUND_TARGET_SCREEN ""
#define MAIN_BACKGROUND_DEAD_ZONE 0.1800f
#define MAIN_BACKGROUND_SENSITIVITY 1.0000f
#define MAIN_BACKGROUND_AUTOMATION_TAGS_JSON "[]"
#define MAIN_BACKGROUND_AUTOMATION_JSON "{}"
#define MAIN_BACKGROUND_EVENT_COUNT 0
#define MAIN_BACKGROUND_EVENTS_JSON "[]"
#define MAIN_BACKGROUND_CLIPPING_MASK_JSON "{}"
#define MAIN_BACKGROUND_ANCHOR_MODE "Center"
#define MAIN_BACKGROUND_ANCHOR_X 0.0000f
#define MAIN_BACKGROUND_ANCHOR_Y 0.0000f
#define MAIN_BACKGROUND_PIXEL_SNAP 1
#define MAIN_BACKGROUND_LOCK_ASPECT 1
#define MAIN_BACKGROUND_KEYFRAME_COUNT 0
static const VxpDesignComponent MAIN_DESIGN_COMPONENTS[1] = {
    {"bg", "Rectangle2D", "", "", 0.0000f, 0.0000f, 0.0000f, 1.0000f, 1.0000f, 240.0000f, 320.0000f, -10, 1} /* z_index: -10 */
};

/* Màn đang mở trong Camera 2D (active screen) */
#define VXP_DESIGN_ACTIVE_COMPONENTS MAIN_DESIGN_COMPONENTS
#define VXP_DESIGN_ACTIVE_COUNT MAIN_COMPONENT_COUNT
#define VXP_DESIGN_ACTIVE_HAS_DESIGN MAIN_HAS_DESIGN

#endif /* VXP_SCENE_BINDINGS_H */
