/*
 * Copyright (c) 2026 PixelRoot32
 * Licensed under the MIT License
 */
#pragma once

#include "core/EngineModules.h"
#if PIXELROOT32_ENABLE_PARTICLES

#include <cstdint>
#include "graphics/Color.h"
#include "math/Scalar.h"

namespace pixelroot32::graphics::particles {

/**
 * @struct ParticleConfig
 * @brief Configuration parameters for a particle emitter.
 *
 * Defines the behavior and appearance of particles generated by an emitter.
 * Allows defining ranges for randomness (speed, life).
 */
struct ParticleConfig {
    Color startColor; ///< Color at the beginning of the particle's life.   
    Color endColor;   ///< Color at the end of the particle's life.

    pixelroot32::math::Scalar minSpeed; ///< Minimum initial speed.
    pixelroot32::math::Scalar maxSpeed; ///< Maximum initial speed.

    pixelroot32::math::Scalar gravity;  ///< Gravity force applied to Y velocity each frame.
    pixelroot32::math::Scalar friction; ///< Air resistance factor (0.0 - 1.0) applied to velocity.

    uint8_t minLife; ///< Minimum lifetime in frames/ticks.
    uint8_t maxLife; ///< Maximum lifetime in frames/ticks.

    bool fadeColor; ///< If true, interpolates color from startColor to endColor.

    pixelroot32::math::Scalar minAngleDeg; ///< Minimum emission angle in degrees (0 = right).
    pixelroot32::math::Scalar maxAngleDeg; ///< Maximum emission angle in degrees.
};

} // namespace pixelroot32::graphics::particles

#endif // PIXELROOT32_ENABLE_PARTICLES
